import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'en' | 'pt' | 'es';

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.dashboard': 'User Dashboard',
    'nav.shop': 'Shop',
    'nav.account': 'My Account',
    'nav.admin': 'Admin',
    'nav.signOut': 'Sign Out',
    'nav.adminPanel': 'Admin Panel',

    'hero.badge': "World's #1 AI-Powered Design Suite",
    'hero.title1': 'Create',
    'hero.titleHighlight': 'Sensational',
    'hero.title2': 'Designs,',
    'hero.title3': 'Graphics & Animations',
    'hero.title4': 'Powered By Artificial Intelligence!',
    'hero.subtitle': "The world's most powerful cloud-based design suite. No tech skills required. Create professional designs in any language — instantly.",
    'hero.cta': 'Get Instant Access Now',
    'hero.viewTools': 'View All Tools',
    'hero.noCreditCard': 'No Credit Card Required',
    'hero.cloudBased': 'Cloud Based',
    'hero.guarantee': '30-Day Guarantee',
    'hero.videoPlaying': 'Video is Playing...',
    'hero.videoSub': 'See DesignActiv in action',
    'hero.soundOn': 'Sound On',
    'hero.soundOff': 'Click For Sound',
    'hero.liveDemo': 'LIVE DEMO',
    'hero.videoCaption': 'Watch how DesignActiv transforms your creative workflow with AI',

    'features.title': 'Why Choose',
    'features.subtitle': 'Everything you need to create professional designs — powered by the latest AI technology.',
    'features.ai.title': 'AI-Powered Technology',
    'features.ai.desc': 'All tools use cutting-edge artificial intelligence to deliver professional results in seconds, not hours.',
    'features.lang.title': 'Works In Any Language',
    'features.lang.desc': 'Create designs in any language and for any market. Our platform supports all languages and character sets.',
    'features.engagement.title': '10X More Engagement',
    'features.engagement.desc': 'Dynamic, AI-enhanced visuals get up to 10 times more engagement than static designs. Dominate your niche.',
    'features.commercial.title': 'Commercial License Included',
    'features.commercial.desc': 'Sell your designs to clients and keep 100% of the profits. Full commercial license is included with every plan.',

    'products.title': 'Our Products',
    'products.banner': "Create Sensational Designs, Graphics & Animations in All Languages With The World's Most Powerful Design Suite Powered By Artificial Intelligence!",
    'products.lessons': 'Number of lessons',

    'pricing.badge': 'Best Value — One-Time Payment',
    'pricing.title': 'Get',
    'pricing.titleHighlight': 'Everything',
    'pricing.title2': 'For One Low Price',
    'pricing.subtitle': 'One-time payment. Lifetime access. No monthly fees ever.',
    'pricing.packTitle': '9 Apps All-in-one Design Pack',
    'pricing.lifetimeAccess': 'Lifetime Access',
    'pricing.whatsIncluded': "What's Included",
    'pricing.allTools': 'All 6 Design Tools',
    'pricing.unlimited': 'Unlimited Usage',
    'pricing.commercial': 'Commercial License',
    'pricing.cloud': 'Cloud Based',
    'pricing.support': '24/7 VIP Support',
    'pricing.templates': 'All Bonus Templates',
    'pricing.agency': 'Agency License',
    'pricing.buyNow': 'Buy Now — $49 Lifetime',
    'pricing.moneyBack': '30-Day Money Back Guarantee — No Questions Asked',
    'pricing.powerfulApps': '6 Powerful Apps',
    'pricing.bonusApps': '3 Bonus Apps — Free!',
    'pricing.bonusNote': 'Bonus apps included at no extra cost!',
    'pricing.oneTime': 'One-Time Payment',
    'pricing.noSubs': 'No subscriptions',
    'pricing.lifetime': 'Lifetime Access',
    'pricing.payOnce': 'Pay once, use forever',
    'pricing.nineApps': '9 Apps Total',
    'pricing.sixPlusThree': '6 + 3 Bonus',

    'testimonials.featuredQuote': 'The service here were beyond my wildest dreams',
    'testimonials.featuredBody': "This world's #1 fully cloud-based software helps you to create designer-quality professional designs without any tech skills.",

    'cta.badge': 'Limited Time Offer',
    'cta.title1': 'Start Creating',
    'cta.titleHighlight': ' Professional Designs ',
    'cta.title2': 'Today!',
    'cta.subtitle': 'Join over 50,000 businesses and creators who use DesignActiv to create stunning visuals every day.',
    'cta.button': 'Get Instant Access Now',
    'cta.guarantee': '30-Day Guarantee',
    'cta.guaranteeDesc': 'Full refund if not satisfied',
    'cta.cloud': 'Cloud Based',
    'cta.cloudDesc': 'Works on any device',
    'cta.instant': 'Instant Access',
    'cta.instantDesc': 'Start using immediately',

    'agency.digitalAgency': 'Digital Agency',

    'footer.desc': 'The world\'s most powerful AI-powered design suite. Create professional designs, graphics, and animations — no tech skills needed.',
    'footer.products': 'Products',
    'footer.company': 'Company',
    'footer.home': 'Home',
    'footer.shop': 'Shop',
    'footer.dashboard': 'User Dashboard',
    'footer.account': 'My Account',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.support': 'Support',
    'footer.secured': 'Secured by SSL & 30-Day Money Back Guarantee',
    'footer.rights': 'All rights reserved.',

    'shop.badge': '9 Powerful AI Tools',
    'shop.title': 'Our Products',
    'shop.allTools': 'All Design Tools',
    'shop.filter': 'AI-Powered',

    'dashboard.title': 'User Dashboard',
    'dashboard.welcome': 'Welcome back! Ready to create?',
    'dashboard.toolsAvail': 'Tools Available',
    'dashboard.totalLessons': 'Total Lessons',
    'dashboard.projectsCreated': 'Projects Created',
    'dashboard.daysActive': 'Days Active',
    'dashboard.yourTools': 'Your Design Tools',
    'dashboard.lessons': 'lessons',
    'dashboard.gettingStarted': 'Getting Started',
    'dashboard.step1': 'Select a design tool from your dashboard',
    'dashboard.step2': 'Watch the tutorial videos to learn the basics',
    'dashboard.step3': 'Start creating your first professional design',
    'dashboard.step4': 'Export and use your designs commercially',

    'account.welcomeBack': 'Welcome Back',
    'account.createAccount': 'Create Account',
    'account.signInDesc': 'Sign in to access your design tools',
    'account.joinDesc': 'Join 50,000+ creators today',
    'account.signIn': 'Sign In',
    'account.create': 'Create Account',
    'account.fullName': 'Full Name',
    'account.email': 'Email Address',
    'account.password': 'Password',
    'account.namePlaceholder': 'Your full name',
    'account.emailPlaceholder': 'your@email.com',
    'account.forgot': 'Forgot your password?',
    'account.agreeTerms': 'By continuing, you agree to our',
    'account.termsLink': 'Terms of Service',
    'account.andText': 'and',
    'account.privacyLink': 'Privacy Policy',
    'account.fillFields': 'Please fill in all required fields.',
    'account.enterName': 'Please enter your full name.',
    'account.passwordLength': 'Password must be at least 6 characters.',
    'account.accountCreated': 'Account created! You can now sign in.',

    'privacy.badge': 'Your Privacy Matters',
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated: January 1, 2025',
    'privacy.intro': 'At DesignActiv, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our services. By using our platform, you agree to the collection and use of information in accordance with this policy.',
    'privacy.collectTitle': 'Information We Collect',
    'privacy.collectBody': 'We collect information you provide directly to us, such as when you create an account, make a purchase, or contact us for support. This includes your name, email address, billing information, and usage data.',
    'privacy.useTitle': 'How We Use Your Information',
    'privacy.useBody': 'We use the information we collect to provide, maintain, and improve our services, process transactions, send you technical notices and support messages, and respond to your comments and questions.',
    'privacy.securityTitle': 'Data Security',
    'privacy.securityBody': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. All data is encrypted in transit and at rest.',
    'privacy.rightsTitle': 'Your Rights',
    'privacy.rightsBody': 'You have the right to access, correct, or delete your personal information at any time. You may also opt out of marketing communications. To exercise these rights, please contact our support team.',
    'privacy.contactTitle': 'Contact Us',
    'privacy.contactBody': 'If you have any questions about this Privacy Policy, please contact us at',

    'terms.title': 'Terms of Service',
    'terms.body': 'By using DesignActiv, you agree to our terms of service. All designs created using our platform may be used for personal and commercial purposes. You may not redistribute, resell, or sublicense the platform itself. We reserve the right to update these terms at any time.',

    'support.title': 'Support Center',
    'support.body': 'Need help? Our support team is available 24/7.',

    'checkout.back': 'Back to Shop',
    'checkout.badge': 'Secure Checkout — SSL Encrypted',
    'checkout.title': 'Complete Your Purchase',
    'checkout.subtitle': '9 Apps All-in-one Design Pack — Lifetime Access',
    'checkout.orderSummary': 'Order Summary',
    'checkout.mainApps': '6 Main Apps',
    'checkout.bonusApps': '3 Bonus Apps — Free!',
    'checkout.total': 'Total',
    'checkout.oneTime': 'One-time payment',
    'checkout.guarantee': '30-Day Money Back Guarantee — Purchase with complete confidence.',
    'checkout.selectMethod': 'Select Payment Method',
    'checkout.pixDesc': 'Pagamento instantaneo',
    'checkout.paypalDesc': 'Pay with PayPal',
    'checkout.stripeDesc': 'Visa, Mastercard, Amex',
    'checkout.pixBadge': 'Pagamento via PIX',
    'checkout.pixInstructions': 'Transfer the value of',
    'checkout.pixKey': 'PIX Key — Mobile',
    'checkout.pixInstant': 'Instant payment 24/7',
    'checkout.pixScan': 'Scan with your bank app',
    'checkout.pixHowTo': 'How it works:',
    'checkout.pixStep1': 'Copy the PIX key above',
    'checkout.pixStep2': 'Open your bank app',
    'checkout.pixStep3': 'Make a PIX transfer of $49 (in R$)',
    'checkout.pixStep4': 'Send the receipt to support@designactiv.com',
    'checkout.pixStep5': 'Receive immediate access within 1 hour',
    'checkout.pixSendReceipt': 'Send Receipt by Email',
    'checkout.paypalTitle': 'Pay with PayPal',
    'checkout.paypalDesc2': "Secure payment via PayPal. You'll be redirected to complete the payment.",
    'checkout.paypalEmail': 'Your Email',
    'checkout.paypalRedirect': "You will be redirected to PayPal's secure website to complete your purchase. Your order will be confirmed immediately after payment.",
    'checkout.paypalButton': 'Pay $49 with PayPal',
    'checkout.stripeTitle': 'Credit / Debit Card',
    'checkout.stripeCards': 'Visa · Mastercard · American Express · Discover',
    'checkout.stripeName': 'Full Name',
    'checkout.stripeEmail': 'Email Address',
    'checkout.stripeCard': 'Card Number',
    'checkout.stripeExpiry': 'Expiry Date',
    'checkout.stripeCvv': 'CVV',
    'checkout.stripeSecured': 'Secured by Stripe — 256-bit SSL encryption',
    'checkout.stripeButton': 'Pay $49 Securely',

    'tool.backToProducts': 'Back to Products',
    'tool.getAccess': 'Get Instant Access Now',
    'tool.moneyBack': '30 Days Money Back Guarantee',
    'tool.beforeDesign': 'Before Design Activ',
    'tool.afterDesign': 'After Design Activ',
    'tool.unlockTitle': 'Unlock',
    'tool.unlockHighlight': 'Limitless Possibilities',
    'tool.unlockSuffix': 'To Profit...',
    'tool.guaranteeTitle': 'Your Purchase Is Backed By Our 30 Day Money Back Guarantee...',
    'tool.guaranteeBody': 'Test drive this incredibly powerful software suite for an attractive low price. Get a full refund if you are not satisfied. Purchase with confidence — no questions asked.',
    'tool.hurryTitle': 'Hurry up... The discounted price will expire very soon...',
    'tool.examplesTitle': 'Few examples of the mind blowing possibilities...',

    'admin.dashboard': 'Dashboard Overview',
    'admin.welcome': 'Welcome back,',
    'admin.totalUsers': 'Total Users',
    'admin.usersAccess': 'Users with Access',
    'admin.adminAccounts': 'Admin Accounts',
    'admin.quickActions': 'Quick Actions',
    'admin.manageUsers': 'Manage Users & Access',
    'admin.updateVideos': 'Update Tool Videos',
    'admin.platformInfo': 'Platform Info',
    'admin.totalTools': 'Total Tools',
    'admin.platform': 'Platform',
    'admin.adminAccess': 'Admin Access',
    'admin.restricted': 'Restricted',
    'admin.userManagement': 'User Management',
    'admin.registeredUsers': 'registered users',
    'admin.refresh': 'Refresh',
    'admin.searchPlaceholder': 'Search by name or email...',
    'admin.user': 'User',
    'admin.joined': 'Joined',
    'admin.adminCol': 'Admin',
    'admin.access': 'Access',
    'admin.actions': 'Actions',
    'admin.noUsers': 'No users found',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.revoke': 'Revoke',
    'admin.grant': 'Grant',
    'admin.toolVideos': 'Tool Videos',
    'admin.videoDesc': 'Update YouTube video IDs for each tool presentation',
    'admin.edit': 'Edit',
    'admin.save': 'Save',
    'admin.saved': 'Saved',
    'admin.videoId': 'YouTube Video ID',
    'admin.titleOverride': 'Title Override',
    'admin.description': 'Description',
    'admin.overview': 'Overview',
    'admin.users': 'User Management',
    'admin.videos': 'Tool Videos',
    'admin.signOut': 'Sign Out',
    'admin.apps': 'apps',
  },
  pt: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Painel do Usuario',
    'nav.shop': 'Loja',
    'nav.account': 'Minha Conta',
    'nav.admin': 'Admin',
    'nav.signOut': 'Sair',
    'nav.adminPanel': 'Painel Admin',

    'hero.badge': 'Suite de Design #1 do Mundo com IA',
    'hero.title1': 'Crie',
    'hero.titleHighlight': 'Designs Sensacionais',
    'hero.title2': ',',
    'hero.title3': 'Graficos e Animacoes',
    'hero.title4': 'Movidos por Inteligencia Artificial!',
    'hero.subtitle': 'A suite de design baseada em nuvem mais poderosa do mundo. Nenhuma habilidade tecnica necessaria. Crie designs profissionais em qualquer idioma — instantaneamente.',
    'hero.cta': 'Obtenha Acesso Instantaneo',
    'hero.viewTools': 'Ver Todas as Ferramentas',
    'hero.noCreditCard': 'Sem Cartao de Credito',
    'hero.cloudBased': 'Baseado em Nuvem',
    'hero.guarantee': 'Garantia de 30 Dias',
    'hero.videoPlaying': 'Video em Reproducao...',
    'hero.videoSub': 'Veja o DesignActiv em acao',
    'hero.soundOn': 'Som Ligado',
    'hero.soundOff': 'Clique para Som',
    'hero.liveDemo': 'DEMO AO VIVO',
    'hero.videoCaption': 'Veja como o DesignActiv transforma seu fluxo de trabalho criativo com IA',

    'features.title': 'Por que Escolher',
    'features.subtitle': 'Tudo que voce precisa para criar designs profissionais — com a mais recente tecnologia de IA.',
    'features.ai.title': 'Tecnologia com IA',
    'features.ai.desc': 'Todas as ferramentas usam inteligencia artificial de ponta para entregar resultados profissionais em segundos.',
    'features.lang.title': 'Funciona em Qualquer Idioma',
    'features.lang.desc': 'Crie designs em qualquer idioma e para qualquer mercado. Nossa plataforma suporta todos os idiomas.',
    'features.engagement.title': '10X Mais Engajamento',
    'features.engagement.desc': 'Visuais dinamicos com IA obtem ate 10 vezes mais engajamento que designs estaticos.',
    'features.commercial.title': 'Licenca Comercial Incluida',
    'features.commercial.desc': 'Venda seus designs para clientes e fique com 100% dos lucros. Licenca comercial completa incluida.',

    'products.title': 'Nossos Produtos',
    'products.banner': 'Crie Designs Sensacionais, Graficos e Animacoes em Todos os Idiomas Com a Suite de Design Mais Poderosa do Mundo Movida por Inteligencia Artificial!',
    'products.lessons': 'Numero de licoes',

    'pricing.badge': 'Melhor Valor — Pagamento Unico',
    'pricing.title': 'Obtenha',
    'pricing.titleHighlight': 'Tudo',
    'pricing.title2': 'Por Um Preco Baixo',
    'pricing.subtitle': 'Pagamento unico. Acesso vitalicio. Sem taxas mensais.',
    'pricing.packTitle': '9 Apps Pacote de Design Completo',
    'pricing.lifetimeAccess': 'Acesso Vitalicio',
    'pricing.whatsIncluded': 'O que esta Incluido',
    'pricing.allTools': 'Todas as 6 Ferramentas de Design',
    'pricing.unlimited': 'Uso Ilimitado',
    'pricing.commercial': 'Licenca Comercial',
    'pricing.cloud': 'Baseado em Nuvem',
    'pricing.support': 'Suporte VIP 24/7',
    'pricing.templates': 'Todos os Templates Bonus',
    'pricing.agency': 'Licenca de Agencia',
    'pricing.buyNow': 'Comprar Agora — $49 Vitalicio',
    'pricing.moneyBack': 'Garantia de 30 Dias — Sem Perguntas',
    'pricing.powerfulApps': '6 Apps Poderosos',
    'pricing.bonusApps': '3 Apps Bonus — Gratis!',
    'pricing.bonusNote': 'Apps bonus incluidos sem custo extra!',
    'pricing.oneTime': 'Pagamento Unico',
    'pricing.noSubs': 'Sem assinaturas',
    'pricing.lifetime': 'Acesso Vitalicio',
    'pricing.payOnce': 'Pague uma vez, use para sempre',
    'pricing.nineApps': '9 Apps no Total',
    'pricing.sixPlusThree': '6 + 3 Bonus',

    'testimonials.featuredQuote': 'O servico aqui superou todos os meus sonhos',
    'testimonials.featuredBody': 'O software #1 do mundo totalmente baseado em nuvem ajuda voce a criar designs profissionais de qualidade sem habilidades tecnicas.',

    'cta.badge': 'Oferta por Tempo Limitado',
    'cta.title1': 'Comece a Criar',
    'cta.titleHighlight': ' Designs Profissionais ',
    'cta.title2': 'Hoje!',
    'cta.subtitle': 'Junte-se a mais de 50.000 empresas e criadores que usam o DesignActiv para criar visuais incriveis todos os dias.',
    'cta.button': 'Obtenha Acesso Instantaneo',
    'cta.guarantee': 'Garantia de 30 Dias',
    'cta.guaranteeDesc': 'Reembolso total se nao satisfeito',
    'cta.cloud': 'Baseado em Nuvem',
    'cta.cloudDesc': 'Funciona em qualquer dispositivo',
    'cta.instant': 'Acesso Instantaneo',
    'cta.instantDesc': 'Comece a usar imediatamente',

    'agency.digitalAgency': 'Agencia Digital',

    'footer.desc': 'A suite de design com IA mais poderosa do mundo. Crie designs profissionais, graficos e animacoes — sem habilidades tecnicas.',
    'footer.products': 'Produtos',
    'footer.company': 'Empresa',
    'footer.home': 'Inicio',
    'footer.shop': 'Loja',
    'footer.dashboard': 'Painel do Usuario',
    'footer.account': 'Minha Conta',
    'footer.privacy': 'Politica de Privacidade',
    'footer.terms': 'Termos de Servico',
    'footer.support': 'Suporte',
    'footer.secured': 'Protegido por SSL e Garantia de 30 Dias',
    'footer.rights': 'Todos os direitos reservados.',

    'shop.badge': '9 Ferramentas de IA Poderosas',
    'shop.title': 'Nossos Produtos',
    'shop.allTools': 'Todas as Ferramentas de Design',
    'shop.filter': 'Com IA',

    'dashboard.title': 'Painel do Usuario',
    'dashboard.welcome': 'Bem-vindo de volta! Pronto para criar?',
    'dashboard.toolsAvail': 'Ferramentas Disponiveis',
    'dashboard.totalLessons': 'Total de Licoes',
    'dashboard.projectsCreated': 'Projetos Criados',
    'dashboard.daysActive': 'Dias Ativos',
    'dashboard.yourTools': 'Suas Ferramentas de Design',
    'dashboard.lessons': 'licoes',
    'dashboard.gettingStarted': 'Primeiros Passos',
    'dashboard.step1': 'Selecione uma ferramenta de design do seu painel',
    'dashboard.step2': 'Assista aos videos tutoriais para aprender o basico',
    'dashboard.step3': 'Comece a criar seu primeiro design profissional',
    'dashboard.step4': 'Exporte e use seus designs comercialmente',

    'account.welcomeBack': 'Bem-vindo de Volta',
    'account.createAccount': 'Criar Conta',
    'account.signInDesc': 'Entre para acessar suas ferramentas de design',
    'account.joinDesc': 'Junte-se a mais de 50.000 criadores hoje',
    'account.signIn': 'Entrar',
    'account.create': 'Criar Conta',
    'account.fullName': 'Nome Completo',
    'account.email': 'Endereco de Email',
    'account.password': 'Senha',
    'account.namePlaceholder': 'Seu nome completo',
    'account.emailPlaceholder': 'seu@email.com',
    'account.forgot': 'Esqueceu sua senha?',
    'account.agreeTerms': 'Ao continuar, voce concorda com nossos',
    'account.termsLink': 'Termos de Servico',
    'account.andText': 'e',
    'account.privacyLink': 'Politica de Privacidade',
    'account.fillFields': 'Por favor, preencha todos os campos obrigatorios.',
    'account.enterName': 'Por favor, insira seu nome completo.',
    'account.passwordLength': 'A senha deve ter pelo menos 6 caracteres.',
    'account.accountCreated': 'Conta criada! Voce ja pode entrar.',

    'privacy.badge': 'Sua Privacidade Importa',
    'privacy.title': 'Politica de Privacidade',
    'privacy.lastUpdated': 'Ultima atualizacao: 1 de Janeiro de 2025',
    'privacy.intro': 'Na DesignActiv, estamos comprometidos em proteger sua privacidade. Esta Politica de Privacidade explica como coletamos, usamos e protegemos suas informacoes quando voce usa nossos servicos.',
    'privacy.collectTitle': 'Informacoes que Coletamos',
    'privacy.collectBody': 'Coletamos informacoes que voce nos fornece diretamente, como ao criar uma conta, fazer uma compra ou entrar em contato com nosso suporte.',
    'privacy.useTitle': 'Como Usamos Suas Informacoes',
    'privacy.useBody': 'Usamos as informacoes coletadas para fornecer, manter e melhorar nossos servicos, processar transacoes e responder suas perguntas.',
    'privacy.securityTitle': 'Seguranca dos Dados',
    'privacy.securityBody': 'Implementamos medidas de seguranca tecnicas e organizacionais apropriadas para proteger suas informacoes pessoais.',
    'privacy.rightsTitle': 'Seus Direitos',
    'privacy.rightsBody': 'Voce tem o direito de acessar, corrigir ou excluir suas informacoes pessoais a qualquer momento.',
    'privacy.contactTitle': 'Contato',
    'privacy.contactBody': 'Se voce tiver alguma duvida sobre esta Politica de Privacidade, entre em contato conosco em',

    'terms.title': 'Termos de Servico',
    'terms.body': 'Ao usar o DesignActiv, voce concorda com nossos termos de servico. Todos os designs criados usando nossa plataforma podem ser usados para fins pessoais e comerciais.',

    'support.title': 'Centro de Suporte',
    'support.body': 'Precisa de ajuda? Nossa equipe de suporte esta disponivel 24/7.',

    'checkout.back': 'Voltar para Loja',
    'checkout.badge': 'Checkout Seguro — Criptografia SSL',
    'checkout.title': 'Complete sua Compra',
    'checkout.subtitle': '9 Apps Pacote de Design Completo — Acesso Vitalicio',
    'checkout.orderSummary': 'Resumo do Pedido',
    'checkout.mainApps': '6 Apps Principais',
    'checkout.bonusApps': '3 Apps Bonus — Gratis!',
    'checkout.total': 'Total',
    'checkout.oneTime': 'Pagamento unico',
    'checkout.guarantee': 'Garantia de 30 Dias — Compre com total confianca.',
    'checkout.selectMethod': 'Selecione o Metodo de Pagamento',
    'checkout.pixDesc': 'Pagamento instantaneo',
    'checkout.paypalDesc': 'Pague com PayPal',
    'checkout.stripeDesc': 'Visa, Mastercard, Amex',
    'checkout.pixBadge': 'Pagamento via PIX',
    'checkout.pixInstructions': 'Transfira o valor de',
    'checkout.pixKey': 'Chave PIX — Celular',
    'checkout.pixInstant': 'Pagamento instantaneo 24/7',
    'checkout.pixScan': 'Escaneie com o app do seu banco',
    'checkout.pixHowTo': 'Como funciona:',
    'checkout.pixStep1': 'Copie a chave PIX acima',
    'checkout.pixStep2': 'Abra o app do seu banco',
    'checkout.pixStep3': 'Faca uma transferencia PIX de $49 (em R$)',
    'checkout.pixStep4': 'Envie o comprovante para support@designactiv.com',
    'checkout.pixStep5': 'Receba acesso imediato em ate 1 hora',
    'checkout.pixSendReceipt': 'Enviar Comprovante por E-mail',
    'checkout.paypalTitle': 'Pague com PayPal',
    'checkout.paypalDesc2': 'Pagamento seguro via PayPal. Voce sera redirecionado para concluir o pagamento.',
    'checkout.paypalEmail': 'Seu Email',
    'checkout.paypalRedirect': 'Voce sera redirecionado para o site seguro do PayPal. Seu pedido sera confirmado imediatamente apos o pagamento.',
    'checkout.paypalButton': 'Pagar $49 com PayPal',
    'checkout.stripeTitle': 'Cartao de Credito / Debito',
    'checkout.stripeCards': 'Visa · Mastercard · American Express · Discover',
    'checkout.stripeName': 'Nome Completo',
    'checkout.stripeEmail': 'Endereco de Email',
    'checkout.stripeCard': 'Numero do Cartao',
    'checkout.stripeExpiry': 'Data de Validade',
    'checkout.stripeCvv': 'CVV',
    'checkout.stripeSecured': 'Protegido por Stripe — Criptografia SSL 256-bit',
    'checkout.stripeButton': 'Pagar $49 com Seguranca',

    'tool.backToProducts': 'Voltar aos Produtos',
    'tool.getAccess': 'Obtenha Acesso Instantaneo',
    'tool.moneyBack': 'Garantia de 30 Dias',
    'tool.beforeDesign': 'Antes do Design Activ',
    'tool.afterDesign': 'Depois do Design Activ',
    'tool.unlockTitle': 'Desbloqueie',
    'tool.unlockHighlight': 'Possibilidades Ilimitadas',
    'tool.unlockSuffix': 'Para Lucrar...',
    'tool.guaranteeTitle': 'Sua Compra e Respaldada por Nossa Garantia de 30 Dias...',
    'tool.guaranteeBody': 'Teste esta suite de software incrivelmente poderosa por um preco atrativo. Reembolso total se nao estiver satisfeito. Compre com confianca.',
    'tool.hurryTitle': 'Corra... O preco com desconto expira muito em breve...',
    'tool.examplesTitle': 'Alguns exemplos das possibilidades incriveis...',

    'admin.dashboard': 'Visao Geral',
    'admin.welcome': 'Bem-vindo de volta,',
    'admin.totalUsers': 'Total de Usuarios',
    'admin.usersAccess': 'Usuarios com Acesso',
    'admin.adminAccounts': 'Contas Admin',
    'admin.quickActions': 'Acoes Rapidas',
    'admin.manageUsers': 'Gerenciar Usuarios e Acesso',
    'admin.updateVideos': 'Atualizar Videos das Ferramentas',
    'admin.platformInfo': 'Info da Plataforma',
    'admin.totalTools': 'Total de Ferramentas',
    'admin.platform': 'Plataforma',
    'admin.adminAccess': 'Acesso Admin',
    'admin.restricted': 'Restrito',
    'admin.userManagement': 'Gerenciamento de Usuarios',
    'admin.registeredUsers': 'usuarios registrados',
    'admin.refresh': 'Atualizar',
    'admin.searchPlaceholder': 'Buscar por nome ou email...',
    'admin.user': 'Usuario',
    'admin.joined': 'Cadastro',
    'admin.adminCol': 'Admin',
    'admin.access': 'Acesso',
    'admin.actions': 'Acoes',
    'admin.noUsers': 'Nenhum usuario encontrado',
    'admin.active': 'Ativo',
    'admin.inactive': 'Inativo',
    'admin.revoke': 'Revogar',
    'admin.grant': 'Conceder',
    'admin.toolVideos': 'Videos das Ferramentas',
    'admin.videoDesc': 'Atualize os IDs dos videos do YouTube para cada ferramenta',
    'admin.edit': 'Editar',
    'admin.save': 'Salvar',
    'admin.saved': 'Salvo',
    'admin.videoId': 'ID do Video YouTube',
    'admin.titleOverride': 'Titulo Personalizado',
    'admin.description': 'Descricao',
    'admin.overview': 'Visao Geral',
    'admin.users': 'Gerenciamento de Usuarios',
    'admin.videos': 'Videos das Ferramentas',
    'admin.signOut': 'Sair',
    'admin.apps': 'apps',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel de Usuario',
    'nav.shop': 'Tienda',
    'nav.account': 'Mi Cuenta',
    'nav.admin': 'Admin',
    'nav.signOut': 'Salir',
    'nav.adminPanel': 'Panel Admin',

    'hero.badge': 'Suite de Diseno #1 del Mundo con IA',
    'hero.title1': 'Crea',
    'hero.titleHighlight': 'Disenos Sensacionales',
    'hero.title2': ',',
    'hero.title3': 'Graficos y Animaciones',
    'hero.title4': 'Impulsados por Inteligencia Artificial!',
    'hero.subtitle': 'La suite de diseno basada en la nube mas poderosa del mundo. Sin habilidades tecnicas requeridas. Crea disenos profesionales en cualquier idioma — al instante.',
    'hero.cta': 'Obtener Acceso Instantaneo',
    'hero.viewTools': 'Ver Todas las Herramientas',
    'hero.noCreditCard': 'Sin Tarjeta de Credito',
    'hero.cloudBased': 'Basado en la Nube',
    'hero.guarantee': 'Garantia de 30 Dias',
    'hero.videoPlaying': 'Video en Reproduccion...',
    'hero.videoSub': 'Mira DesignActiv en accion',
    'hero.soundOn': 'Sonido Activado',
    'hero.soundOff': 'Clic para Sonido',
    'hero.liveDemo': 'DEMO EN VIVO',
    'hero.videoCaption': 'Mira como DesignActiv transforma tu flujo de trabajo creativo con IA',

    'features.title': 'Por que Elegir',
    'features.subtitle': 'Todo lo que necesitas para crear disenos profesionales — con la ultima tecnologia de IA.',
    'features.ai.title': 'Tecnologia con IA',
    'features.ai.desc': 'Todas las herramientas usan inteligencia artificial de vanguardia para entregar resultados profesionales en segundos.',
    'features.lang.title': 'Funciona en Cualquier Idioma',
    'features.lang.desc': 'Crea disenos en cualquier idioma y para cualquier mercado. Nuestra plataforma soporta todos los idiomas.',
    'features.engagement.title': '10X Mas Engagement',
    'features.engagement.desc': 'Los visuales dinamicos con IA obtienen hasta 10 veces mas engagement que los disenos estaticos.',
    'features.commercial.title': 'Licencia Comercial Incluida',
    'features.commercial.desc': 'Vende tus disenos a clientes y queda con el 100% de las ganancias. Licencia comercial completa incluida.',

    'products.title': 'Nuestros Productos',
    'products.banner': 'Crea Disenos Sensacionales, Graficos y Animaciones en Todos los Idiomas Con la Suite de Diseno Mas Poderosa del Mundo Impulsada por Inteligencia Artificial!',
    'products.lessons': 'Numero de lecciones',

    'pricing.badge': 'Mejor Valor — Pago Unico',
    'pricing.title': 'Obtener',
    'pricing.titleHighlight': 'Todo',
    'pricing.title2': 'Por Un Bajo Precio',
    'pricing.subtitle': 'Pago unico. Acceso de por vida. Sin cuotas mensuales.',
    'pricing.packTitle': '9 Apps Paquete de Diseno Completo',
    'pricing.lifetimeAccess': 'Acceso de Por Vida',
    'pricing.whatsIncluded': 'Que esta Incluido',
    'pricing.allTools': 'Las 6 Herramientas de Diseno',
    'pricing.unlimited': 'Uso Ilimitado',
    'pricing.commercial': 'Licencia Comercial',
    'pricing.cloud': 'Basado en la Nube',
    'pricing.support': 'Soporte VIP 24/7',
    'pricing.templates': 'Todos los Templates Bonus',
    'pricing.agency': 'Licencia de Agencia',
    'pricing.buyNow': 'Comprar Ahora — $49 De Por Vida',
    'pricing.moneyBack': 'Garantia de 30 Dias — Sin Preguntas',
    'pricing.powerfulApps': '6 Apps Poderosas',
    'pricing.bonusApps': '3 Apps Bonus — Gratis!',
    'pricing.bonusNote': 'Apps bonus incluidas sin costo extra!',
    'pricing.oneTime': 'Pago Unico',
    'pricing.noSubs': 'Sin suscripciones',
    'pricing.lifetime': 'Acceso de Por Vida',
    'pricing.payOnce': 'Paga una vez, usa para siempre',
    'pricing.nineApps': '9 Apps en Total',
    'pricing.sixPlusThree': '6 + 3 Bonus',

    'testimonials.featuredQuote': 'El servicio aqui supero todos mis suenos',
    'testimonials.featuredBody': 'El software #1 del mundo completamente basado en la nube te ayuda a crear disenos profesionales de calidad sin habilidades tecnicas.',

    'cta.badge': 'Oferta por Tiempo Limitado',
    'cta.title1': 'Empieza a Crear',
    'cta.titleHighlight': ' Disenos Profesionales ',
    'cta.title2': 'Hoy!',
    'cta.subtitle': 'Unete a mas de 50,000 empresas y creadores que usan DesignActiv para crear visuales increibles todos los dias.',
    'cta.button': 'Obtener Acceso Instantaneo',
    'cta.guarantee': 'Garantia de 30 Dias',
    'cta.guaranteeDesc': 'Reembolso total si no esta satisfecho',
    'cta.cloud': 'Basado en la Nube',
    'cta.cloudDesc': 'Funciona en cualquier dispositivo',
    'cta.instant': 'Acceso Instantaneo',
    'cta.instantDesc': 'Empieza a usar inmediatamente',

    'agency.digitalAgency': 'Agencia Digital',

    'footer.desc': 'La suite de diseno con IA mas poderosa del mundo. Crea disenos profesionales, graficos y animaciones — sin habilidades tecnicas.',
    'footer.products': 'Productos',
    'footer.company': 'Empresa',
    'footer.home': 'Inicio',
    'footer.shop': 'Tienda',
    'footer.dashboard': 'Panel de Usuario',
    'footer.account': 'Mi Cuenta',
    'footer.privacy': 'Politica de Privacidad',
    'footer.terms': 'Terminos de Servicio',
    'footer.support': 'Soporte',
    'footer.secured': 'Protegido por SSL y Garantia de 30 Dias',
    'footer.rights': 'Todos los derechos reservados.',

    'shop.badge': '9 Herramientas de IA Poderosas',
    'shop.title': 'Nuestros Productos',
    'shop.allTools': 'Todas las Herramientas de Diseno',
    'shop.filter': 'Con IA',

    'dashboard.title': 'Panel de Usuario',
    'dashboard.welcome': 'Bienvenido de vuelta! Listo para crear?',
    'dashboard.toolsAvail': 'Herramientas Disponibles',
    'dashboard.totalLessons': 'Total de Lecciones',
    'dashboard.projectsCreated': 'Proyectos Creados',
    'dashboard.daysActive': 'Dias Activos',
    'dashboard.yourTools': 'Tus Herramientas de Diseno',
    'dashboard.lessons': 'lecciones',
    'dashboard.gettingStarted': 'Primeros Pasos',
    'dashboard.step1': 'Selecciona una herramienta de diseno de tu panel',
    'dashboard.step2': 'Mira los videos tutoriales para aprender lo basico',
    'dashboard.step3': 'Empieza a crear tu primer diseno profesional',
    'dashboard.step4': 'Exporta y usa tus disenos comercialmente',

    'account.welcomeBack': 'Bienvenido de Vuelta',
    'account.createAccount': 'Crear Cuenta',
    'account.signInDesc': 'Inicia sesion para acceder a tus herramientas',
    'account.joinDesc': 'Unete a mas de 50,000 creadores hoy',
    'account.signIn': 'Iniciar Sesion',
    'account.create': 'Crear Cuenta',
    'account.fullName': 'Nombre Completo',
    'account.email': 'Direccion de Email',
    'account.password': 'Contrasena',
    'account.namePlaceholder': 'Tu nombre completo',
    'account.emailPlaceholder': 'tu@email.com',
    'account.forgot': 'Olvidaste tu contrasena?',
    'account.agreeTerms': 'Al continuar, aceptas nuestros',
    'account.termsLink': 'Terminos de Servicio',
    'account.andText': 'y',
    'account.privacyLink': 'Politica de Privacidad',
    'account.fillFields': 'Por favor, completa todos los campos requeridos.',
    'account.enterName': 'Por favor, ingresa tu nombre completo.',
    'account.passwordLength': 'La contrasena debe tener al menos 6 caracteres.',
    'account.accountCreated': 'Cuenta creada! Ya puedes iniciar sesion.',

    'privacy.badge': 'Tu Privacidad Importa',
    'privacy.title': 'Politica de Privacidad',
    'privacy.lastUpdated': 'Ultima actualizacion: 1 de Enero de 2025',
    'privacy.intro': 'En DesignActiv, estamos comprometidos a proteger tu privacidad. Esta Politica de Privacidad explica como recopilamos, usamos y protegemos tu informacion.',
    'privacy.collectTitle': 'Informacion que Recopilamos',
    'privacy.collectBody': 'Recopilamos informacion que nos proporcionas directamente, como al crear una cuenta, hacer una compra o contactar a nuestro soporte.',
    'privacy.useTitle': 'Como Usamos Tu Informacion',
    'privacy.useBody': 'Usamos la informacion recopilada para proporcionar, mantener y mejorar nuestros servicios, procesar transacciones y responder tus preguntas.',
    'privacy.securityTitle': 'Seguridad de los Datos',
    'privacy.securityBody': 'Implementamos medidas de seguridad tecnicas y organizacionales apropiadas para proteger tu informacion personal.',
    'privacy.rightsTitle': 'Tus Derechos',
    'privacy.rightsBody': 'Tienes el derecho de acceder, corregir o eliminar tu informacion personal en cualquier momento.',
    'privacy.contactTitle': 'Contacto',
    'privacy.contactBody': 'Si tienes alguna pregunta sobre esta Politica de Privacidad, contactanos en',

    'terms.title': 'Terminos de Servicio',
    'terms.body': 'Al usar DesignActiv, aceptas nuestros terminos de servicio. Todos los disenos creados usando nuestra plataforma pueden usarse para fines personales y comerciales.',

    'support.title': 'Centro de Soporte',
    'support.body': 'Necesitas ayuda? Nuestro equipo de soporte esta disponible 24/7.',

    'checkout.back': 'Volver a la Tienda',
    'checkout.badge': 'Pago Seguro — Encriptacion SSL',
    'checkout.title': 'Completa tu Compra',
    'checkout.subtitle': '9 Apps Paquete de Diseno Completo — Acceso de Por Vida',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.mainApps': '6 Apps Principales',
    'checkout.bonusApps': '3 Apps Bonus — Gratis!',
    'checkout.total': 'Total',
    'checkout.oneTime': 'Pago unico',
    'checkout.guarantee': 'Garantia de 30 Dias — Compra con total confianza.',
    'checkout.selectMethod': 'Selecciona el Metodo de Pago',
    'checkout.pixDesc': 'Pago instantaneo',
    'checkout.paypalDesc': 'Paga con PayPal',
    'checkout.stripeDesc': 'Visa, Mastercard, Amex',
    'checkout.pixBadge': 'Pago via PIX',
    'checkout.pixInstructions': 'Transfiere el valor de',
    'checkout.pixKey': 'Clave PIX — Celular',
    'checkout.pixInstant': 'Pago instantaneo 24/7',
    'checkout.pixScan': 'Escanea con la app de tu banco',
    'checkout.pixHowTo': 'Como funciona:',
    'checkout.pixStep1': 'Copia la clave PIX arriba',
    'checkout.pixStep2': 'Abre la app de tu banco',
    'checkout.pixStep3': 'Haz una transferencia PIX de $49 (en R$)',
    'checkout.pixStep4': 'Envia el comprobante a support@designactiv.com',
    'checkout.pixStep5': 'Recibe acceso inmediato en hasta 1 hora',
    'checkout.pixSendReceipt': 'Enviar Comprobante por Email',
    'checkout.paypalTitle': 'Paga con PayPal',
    'checkout.paypalDesc2': 'Pago seguro via PayPal. Seras redirigido para completar el pago.',
    'checkout.paypalEmail': 'Tu Email',
    'checkout.paypalRedirect': 'Seras redirigido al sitio seguro de PayPal. Tu pedido sera confirmado inmediatamente despues del pago.',
    'checkout.paypalButton': 'Pagar $49 con PayPal',
    'checkout.stripeTitle': 'Tarjeta de Credito / Debito',
    'checkout.stripeCards': 'Visa · Mastercard · American Express · Discover',
    'checkout.stripeName': 'Nombre Completo',
    'checkout.stripeEmail': 'Direccion de Email',
    'checkout.stripeCard': 'Numero de Tarjeta',
    'checkout.stripeExpiry': 'Fecha de Vencimiento',
    'checkout.stripeCvv': 'CVV',
    'checkout.stripeSecured': 'Protegido por Stripe — Encriptacion SSL 256-bit',
    'checkout.stripeButton': 'Pagar $49 de Forma Segura',

    'tool.backToProducts': 'Volver a Productos',
    'tool.getAccess': 'Obtener Acceso Instantaneo',
    'tool.moneyBack': 'Garantia de 30 Dias',
    'tool.beforeDesign': 'Antes de Design Activ',
    'tool.afterDesign': 'Despues de Design Activ',
    'tool.unlockTitle': 'Desbloquea',
    'tool.unlockHighlight': 'Posibilidades Ilimitadas',
    'tool.unlockSuffix': 'Para Lucrar...',
    'tool.guaranteeTitle': 'Tu Compra esta Respaldada por Nuestra Garantia de 30 Dias...',
    'tool.guaranteeBody': 'Prueba esta suite de software increiblemente poderosa por un precio atractivo. Reembolso total si no estas satisfecho. Compra con confianza.',
    'tool.hurryTitle': 'Apurate... El precio con descuento expirara muy pronto...',
    'tool.examplesTitle': 'Algunos ejemplos de las posibilidades increibles...',

    'admin.dashboard': 'Vision General',
    'admin.welcome': 'Bienvenido de vuelta,',
    'admin.totalUsers': 'Total de Usuarios',
    'admin.usersAccess': 'Usuarios con Acceso',
    'admin.adminAccounts': 'Cuentas Admin',
    'admin.quickActions': 'Acciones Rapidas',
    'admin.manageUsers': 'Gestionar Usuarios y Acceso',
    'admin.updateVideos': 'Actualizar Videos de Herramientas',
    'admin.platformInfo': 'Info de Plataforma',
    'admin.totalTools': 'Total de Herramientas',
    'admin.platform': 'Plataforma',
    'admin.adminAccess': 'Acceso Admin',
    'admin.restricted': 'Restringido',
    'admin.userManagement': 'Gestion de Usuarios',
    'admin.registeredUsers': 'usuarios registrados',
    'admin.refresh': 'Actualizar',
    'admin.searchPlaceholder': 'Buscar por nombre o email...',
    'admin.user': 'Usuario',
    'admin.joined': 'Registro',
    'admin.adminCol': 'Admin',
    'admin.access': 'Acceso',
    'admin.actions': 'Acciones',
    'admin.noUsers': 'No se encontraron usuarios',
    'admin.active': 'Activo',
    'admin.inactive': 'Inactivo',
    'admin.revoke': 'Revocar',
    'admin.grant': 'Conceder',
    'admin.toolVideos': 'Videos de Herramientas',
    'admin.videoDesc': 'Actualiza los IDs de video de YouTube para cada herramienta',
    'admin.edit': 'Editar',
    'admin.save': 'Guardar',
    'admin.saved': 'Guardado',
    'admin.videoId': 'ID del Video YouTube',
    'admin.titleOverride': 'Titulo Personalizado',
    'admin.description': 'Descripcion',
    'admin.overview': 'Vision General',
    'admin.users': 'Gestion de Usuarios',
    'admin.videos': 'Videos de Herramientas',
    'admin.signOut': 'Salir',
    'admin.apps': 'apps',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem('da_lang');
    if (saved === 'pt' || saved === 'es') return saved;
    return 'en';
  });

  const changeLang = (newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem('da_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
